// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type User struct {
	ID     string `json:"id"`
	Email  string `json:"email"`
	UserID string `json:"userID"`
}

type UserInput struct {
	Email  *string `json:"email"`
	UserID *string `json:"userID"`
}
